name: 续订:Docker

on:
#  push:
  #schedule:
    # run every 3 days on UTC 0/1/2am (8/9/10am CN time)
  #   - cron: '0 1 */2 * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
#     runs-on: self-hosted
    runs-on: ubuntu-latest
    environment: IMAGES
    steps:
      - name: "run"
        run: |
          docker pull zakkoree/woiden_extend:latest
          docker run -e USERNAME=${{ secrets.USERNAME }} \
          -e PASSWORD=${{ secrets.PASSWORD }} \
          -e TWOCAPTCHA_TOKEN=${{ secrets.TWOCAPTCHA_TOKEN }} \
          -e APP_ID=${{ secrets.APP_ID }} \
          -e API_KEY=${{ secrets.API_KEY }} \
          -e SECRET_KEY=${{ secrets.SECRET_KEY }} \
          -e ASR_CHOICE=${{ secrets.ASR_CHOICE }} \
          -e IBM_URL=${{ secrets.IBM_URL }} \
          zakkoree/woiden_extend:latest
