name: 续订

on: 
  workflow_dispatch:
  schedule:
    - cron: "0 0,8,16 * * *"
env:
  USERNAME: ${{ secrets.USERNAME }}
  PASSWORD: ${{ secrets.PASSWORD }}
  APP_ID: ${{ secrets.APP_ID }}
  API_KEY: ${{ secrets.API_KEY }}
  SECRET_KEY: ${{ secrets.SECRET_KEY }}
  TWOCAPTCHA_TOKEN: ${{ secrets.TWOCAPTCHA_TOKEN }}
  TELE_ID: ${{ secrets.TELE_ID }}
  TELE_TOKEN: ${{ secrets.TELE_TOKEN }}
  ASR_CHOICE: ${{ secrets.ASR_CHOICE }}
  IBM_URL: ${{ secrets.IBM_URL }}

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      check: ${{ steps.check.outputs.check }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        
      - id: check
        name: check
        run: |
          renewTime=$(cat renewTime)
          interval=$(( ($(date -d "now" +%s) - $(date -d "$renewTime" +%s))/(24*60*60) )) 2>&1 
          if [ "$?" = 0 ] && [ $interval -gt 0 ] && [ $interval -lt 8 ]; then
            echo "check=success" >> $GITHUB_OUTPUT
          else
            echo "check=fail" >> $GITHUB_OUTPUT
          fi
  renew:
    runs-on: ubuntu-latest
    needs: check
    if: needs.check.outputs.check == 'success'
    steps:
#         - run: echo ${{needs.check.outputs.check}} 
      - name: Clone repository
        uses: actions/checkout@v3
#         sudo sed -i 's/azure\.//' /etc/apt/sources.list &&   防止apt安装失败
      - name: Install Python
        run: |
          sudo sed -i 's/azure\.//' /etc/apt/sources.list && sudo apt update && \
          sudo apt install python3 
      
      - name: requirements
        run: |
          pip3 install -r ./requirements.txt
          playwright install --with-deps

      - name: renew
        run: |
          git config --local user.email "1223105850@qq.com"
          git config --local user.name "Zakkoree"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          python3 main.py
          a=$(cat renewTime)
          b=${a//-/.}
          sed -i -e "s:badge/".*"-activity:badge/"$b"-activity:g" README.md
          git commit -a -m "download file"
          git push
  
